### ISSUE TITLE
ImageGlass 8.5.1.22 not start anymore

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#1280]
I just updated ImageGlass to the very last one 8.5.1.22 and now the app is not starting anymore (when i double click on a icon I can see the imageglass.exe appearing in the task manager but it's disappear suddenly)

**Comment by d2phap** [comment]
It sounds like config file's problem.
Can you open `%AppData%\ImageGlass` folder, and delete `igconfig.xml` file?

**Comment by Zeus64** [comment]
Hello, even deleting igconfig.xml do not help. Note also that on my machine ImageGlass is installed in C:\Program Files\ImageGlass\ not in %AppData%\ImageGlass

**Comment by fire-eggs** [comment]
This sort of behavior usually means a dependency is missing, or ImageGlass is crashing early on.

On the off-chance you upgraded from a much earlier version of ImageGlass, you want to insure that you have the correct [.NET
framework](https://dotnet.microsoft.com/download/dotnet-framework/net48) installed, and the latest Visual C Runtime [(64-bit)](https://aka.ms/vs/17/release/vc_redist.x64.exe) or [(32-bit)](https://aka.ms/vs/17/release/vc_redist.x86.exe).

Does ImageGlass start if executed from the Start Menu (i.e. _not_ by double-clicking an image)?

**Comment by Zeus64** [comment]
I upgraded from the previous version of ImageGlass (updated 2 months ago). 

>> Does ImageGlass start if executed from the Start Menu
no, well ImageGlass start (I can see the exe in the taskmanager) but close immediately after and show nothing.

the only think is that I installed imageGlass in :\Program Files\ImageGlass\

**Comment by d2phap** [comment]
@Zeus64 
Can you send me the `igconfig.xml` file in `%AppData%\ImageGlass` folder?
Or a video also helps.

Thanks

**Comment by Zeus64** [comment]
I have 2 igconfig.xml :

C:\Users\zeus\AppData\Roaming\ImageGlass\igconfig.xml

```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="IsSlideshow" value="False" />
      <Item key="IsShowSlideshowCountdown" value="True" />
      <Item key="IsRandomSlideshowInterval" value="False" />
      <Item key="IsFullScreen" value="True" />
      <Item key="IsShowThumbnail" value="False" />
      <Item key="IsCenterImage" value="True" />
      <Item key="IsColorPickerRGBA" value="True" />
      <Item key="IsColorPickerHEXA" value="True" />
      <Item key="IsColorPickerHSLA" value="True" />
      <Item key="IsColorPickerHSVA" value="True" />
      <Item key="IsShowWelcome" value="True" />
      <Item key="IsShowToolBar" value="False" />
      <Item key="IsShowThumbnailScrollbar" value="False" />
      <Item key="IsLoopBackSlideshow" value="True" />
      <Item key="IsLoopBackViewer" value="True" />
      <Item key="IsPressESCToQuit" value="True" />
      <Item key="IsShowCheckerBoard" value="False" />
      <Item key="IsAllowMultiInstances" value="True" />
      <Item key="IsWindowAlwaysOnTop" value="False" />
      <Item key="IsWindowFrameless" value="False" />
      <Item key="IsThumbnailHorizontal" value="True" />
      <Item key="IsConfirmationDelete" value="False" />
      <Item key="IsScrollbarsVisible" value="False" />
      <Item key="IsSaveAfterRotating" value="False" />
      <Item key="IsPreserveModifiedDate" value="True" />
      <Item key="IsNewVersionAvailable" value="True" />
      <Item key="IsDisplayBasenameOfImage" value="False" />
      <Item key="IsCenterToolbar" value="True" />
      <Item key="IsOpenLastSeenImage" value="False" />
      <Item key="IsApplyColorProfileForAll" value="False" />
      <Item key="IsShowNavigationButtons" value="False" />
      <Item key="IsShowCheckerboardOnlyImageRegion" value="False" />
      <Item key="IsRecursiveLoading" value="False" />
      <Item key="IsUseFileExplorerSortOrder" value="True" />
      <Item key="IsGroupImagesByDirectory" value="False" />
      <Item key="IsShowingHiddenImages" value="False" />
      <Item key="IsShowColorPickerOnStartup" value="False" />
      <Item key="IsShowPageNavOnStartup" value="False" />
      <Item key="IsShowPageNavAuto" value="False" />
      <Item key="IsWindowFit" value="False" />
      <Item key="IsCenterWindowFit" value="True" />
      <Item key="IsShowToast" value="True" />
      <Item key="IsUseTouchGesture" value="True" />
      <Item key="IsHideTooltips" value="False" />
      <Item key="IsExifToolAlwaysOnTop" value="True" />
      <Item key="IsUseEmptyTitleBar" value="False" />
      <Item key="FirstLaunchVersion" value="5" />
      <Item key="SlideShowInterval" value="5" />
      <Item key="SlideShowIntervalTo" value="5" />
      <Item key="ThumbnailDimension" value="96" />
      <Item key="ThumbnailBarWidth" value="1187" />
      <Item key="ImageBoosterCachedCount" value="1" />
      <Item key="ZoomLockValue" value="100" />
      <Item key="ToolbarIconHeight" value="22" />
      <Item key="ImageEditQuality" value="100" />
      <Item key="FrmMainWindowState" value="Normal" />
      <Item key="FrmSettingsWindowState" value="Normal" />
      <Item key="FrmExifToolWindowState" value="Normal" />
      <Item key="ImageLoadingOrder" value="Name" />
      <Item key="ImageLoadingOrderType" value="Asc" />
      <Item key="MouseWheelAction" value="BrowseImages" />
      <Item key="MouseWheelCtrlAction" value="ScrollVertically" />
      <Item key="MouseWheelShiftAction" value="ScrollHorizontally" />
      <Item key="MouseWheelAltAction" value="DoNothing" />
      <Item key="ZoomMode" value="AutoZoom" />
      <Item key="ZoomOptimizationMethod" value="Auto" />
      <Item key="ToolbarPosition" value="Top" />
      <Item key="AfterEditingAction" value="Nothing" />
      <Item key="ColorProfile" value="sRGB" />
      <Item key="ToolbarButtons" value="btnBack;btnNext;Separator;btnRotateLeft;btnRotateRight;btnFlipHorz;btnFlipVert;btnCrop;Separator;btnAutoZoom;btnZoomLock;btnScaletoWidth;btnScaletoHeight;btnScaleToFit;btnScaleToFill;Separator;btnOpen;btnRefresh;Separator;btnWindowFit;btnFullScreen;btnSlideShow;Separator;btnThumb;btnCheckedBackground;btnDelete;" />
      <Item key="AutoUpdate" value="1/24/2022 11:41:39" />
      <Item key="LastSeenImagePath" value="C:\Program Files\ImageGlass\default.jpg" />
      <Item key="ExifToolExePath" value="" />
      <Item key="ZoomLevels" value="5;10;15;20;30;40;50;60;70;80;90;100;125;150;175;200;250;300;350;400;500;600;700;800;1000;1200;1500;1800;2100;2500;3000;3500" />
      <Item key="EditApps" value="[.avif|||][.b64|||][.bmp|||][.cur|||][.cut|||][.dds|||][.dib|||][.emf|||][.exif|||][.gif|||][.heic|||][.heif|||][.ico|||][.jfif|||][.jp2|||][.jpe|||][.jpeg|||][.jpg|||][.pbm|||][.pcx|||][.pgm|||][.png|||][.ppm|||][.psb|||][.svg|||][.tif|||][.tiff|||][.webp|||][.wmf|||][.wpg|||][.xbm|||][.xpm|||][.exr|||][.hdr|||][.psd|||][.tga|||][.3fr|||][.ari|||][.arw|||][.bay|||][.crw|||][.cr2|||][.cr3|||][.cap|||][.dcs|||][.dcr|||][.dng|||][.drf|||][.eip|||][.erf|||][.fff|||][.gpr|||][.iiq|||][.k25|||][.kdc|||][.mdc|||][.mef|||][.mos|||][.mrw|||][.nef|||][.nrw|||][.obm|||][.orf|||][.pef|||][.ptx|||][.pxn|||][.r3d|||][.raf|||][.raw|||][.rwl|||][.rw2|||][.rwz|||][.sr2|||][.srf|||][.srw|||][.x3f|||]" />
      <Item key="AllFormats" value="*.avif;*.b64;*.bmp;*.cur;*.cut;*.dds;*.dib;*.emf;*.exif;*.gif;*.heic;*.heif;*.ico;*.jfif;*.jp2;*.jpe;*.jpeg;*.jpg;*.pbm;*.pcx;*.pgm;*.png;*.ppm;*.psb;*.svg;*.tif;*.tiff;*.webp;*.wmf;*.wpg;*.xbm;*.xpm;*.exr;*.hdr;*.psd;*.tga;*.3fr;*.ari;*.arw;*.bay;*.crw;*.cr2;*.cr3;*.cap;*.dcs;*.dcr;*.dng;*.drf;*.eip;*.erf;*.fff;*.gpr;*.iiq;*.k25;*.kdc;*.mdc;*.mef;*.mos;*.mrw;*.nef;*.nrw;*.obm;*.orf;*.pef;*.ptx;*.pxn;*.r3d;*.raf;*.raw;*.rwl;*.rw2;*.rwz;*.sr2;*.srf;*.srw;*.x3f;" />
      <Item key="KeyComboActions" value="LeftRight:PrevNextImage;PageUpDown:PrevNextImage;SpaceBack:PrevNextImage;UpDown:PanUpDown;" />
      <Item key="BackgroundColor" value="#3A3C3D" />
      <Item key="FrmMainWindowBound" value="280;125;1300;800" />
      <Item key="FrmSettingsWindowBound" value="280;125;1050;750" />
      <Item key="FrmExifToolWindowBound" value="280;125;800;600" />
      <Item key="Language" value="Languages" />
      <Item key="Theme" value="Kobe" />
      <Item key="ExifToolCommandArgs" value="" />
      <Item key="IsUseRawThumbnail" value="False" />
      <Item key="IsHideToolbarInFullscreen" value="False" />
      <Item key="IsHideThumbnailBarInFullscreen" value="False" />
      <Item key="SinglePageFormats" value="*.heic;*.heif;*.psd;" />
    </Content>
  </Configuration>
</ImageGlass>
```


and

c:\Program Files\ImageGlass\igconfig.xml

```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="IsSlideshow" value="False" />
      <Item key="IsShowSlideshowCountdown" value="True" />
      <Item key="IsRandomSlideshowInterval" value="False" />
      <Item key="IsFullScreen" value="True" />
      <Item key="IsShowThumbnail" value="False" />
      <Item key="IsCenterImage" value="True" />
      <Item key="IsColorPickerRGBA" value="True" />
      <Item key="IsColorPickerHEXA" value="True" />
      <Item key="IsColorPickerHSLA" value="True" />
      <Item key="IsColorPickerHSVA" value="True" />
      <Item key="IsShowWelcome" value="False" />
      <Item key="IsShowToolBar" value="True" />
      <Item key="IsShowThumbnailScrollbar" value="False" />
      <Item key="IsLoopBackSlideshow" value="True" />
      <Item key="IsLoopBackViewer" value="False" />
      <Item key="IsPressESCToQuit" value="True" />
      <Item key="IsShowCheckerBoard" value="True" />
      <Item key="IsAllowMultiInstances" value="False" />
      <Item key="IsWindowAlwaysOnTop" value="False" />
      <Item key="IsWindowFrameless" value="False" />
      <Item key="IsThumbnailHorizontal" value="True" />
      <Item key="IsConfirmationDelete" value="True" />
      <Item key="IsScrollbarsVisible" value="False" />
      <Item key="IsSaveAfterRotating" value="False" />
      <Item key="IsPreserveModifiedDate" value="True" />
      <Item key="IsNewVersionAvailable" value="True" />
      <Item key="IsDisplayBasenameOfImage" value="False" />
      <Item key="IsCenterToolbar" value="True" />
      <Item key="IsOpenLastSeenImage" value="False" />
      <Item key="IsApplyColorProfileForAll" value="False" />
      <Item key="IsShowNavigationButtons" value="False" />
      <Item key="IsShowCheckerboardOnlyImageRegion" value="False" />
      <Item key="IsRecursiveLoading" value="False" />
      <Item key="IsUseFileExplorerSortOrder" value="True" />
      <Item key="IsGroupImagesByDirectory" value="False" />
      <Item key="IsShowingHiddenImages" value="False" />
      <Item key="IsShowColorPickerOnStartup" value="False" />
      <Item key="IsShowPageNavOnStartup" value="False" />
      <Item key="IsShowPageNavAuto" value="True" />
      <Item key="IsWindowFit" value="False" />
      <Item key="IsCenterWindowFit" value="True" />
      <Item key="IsShowToast" value="True" />
      <Item key="IsUseTouchGesture" value="False" />
      <Item key="IsHideTooltips" value="False" />
      <Item key="IsExifToolAlwaysOnTop" value="True" />
      <Item key="IsUseEmptyTitleBar" value="False" />
      <Item key="FirstLaunchVersion" value="5" />
      <Item key="SlideShowInterval" value="5" />
      <Item key="SlideShowIntervalTo" value="5" />
      <Item key="ThumbnailDimension" value="96" />
      <Item key="ThumbnailBarWidth" value="1448" />
      <Item key="ImageBoosterCachedCount" value="10" />
      <Item key="ZoomLockValue" value="100" />
      <Item key="ToolbarIconHeight" value="22" />
      <Item key="ImageEditQuality" value="100" />
      <Item key="FrmMainWindowState" value="Normal" />
      <Item key="FrmSettingsWindowState" value="Normal" />
      <Item key="FrmExifToolWindowState" value="Normal" />
      <Item key="ImageLoadingOrder" value="Name" />
      <Item key="ImageLoadingOrderType" value="Asc" />
      <Item key="MouseWheelAction" value="BrowseImages" />
      <Item key="MouseWheelCtrlAction" value="ScrollVertically" />
      <Item key="MouseWheelShiftAction" value="ScrollHorizontally" />
      <Item key="MouseWheelAltAction" value="DoNothing" />
      <Item key="ZoomMode" value="AutoZoom" />
      <Item key="ZoomOptimizationMethod" value="Auto" />
      <Item key="ToolbarPosition" value="Top" />
      <Item key="AfterEditingAction" value="Close" />
      <Item key="ColorProfile" value="sRGB" />
      <Item key="ToolbarButtons" value="btnBack;btnNext;Separator;btnRotateLeft;btnRotateRight;btnFlipHorz;btnFlipVert;btnCrop;Separator;btnAutoZoom;btnZoomLock;btnScaletoWidth;btnScaletoHeight;btnScaleToFit;btnScaleToFill;Separator;btnOpen;btnRefresh;Separator;btnWindowFit;btnFullScreen;btnSlideShow;Separator;btnThumb;btnCheckedBackground;btnDelete;" />
      <Item key="AutoUpdate" value="1/30/2022 18:22:01" />
      <Item key="LastSeenImagePath" value="D:\Photos\ToUpload\Cannes Beach\_serie1\img_5967_original_5025350503_o.png" />
      <Item key="ExifToolExePath" value="C:\Program Files\ExifTool\exiftool.exe" />
      <Item key="ZoomLevels" value="5;10;15;20;30;40;50;60;70;80;90;100;125;150;175;200;250;300;350;400;500;600;700;800;1000;1200;1500;1800;2100;2500;3000;3500" />
      <Item key="EditApps" value="[.avif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.b64|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.bmp|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.cur|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.cut|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.dds|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.dib|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.emf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.exif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.gif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.heic|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.heif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.ico|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.jfif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.jp2|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.jpe|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.jpeg|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.jpg|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.pbm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.pcx|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.pgm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.png|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.ppm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.psb|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.svg|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.tif|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.tiff|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.webp|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.wmf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.wpg|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.xbm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.xpm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.exr|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.hdr|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.psd|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.tga|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.3fr|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.ari|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.arw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.bay|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.crw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.cr2|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.cr3|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.cap|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.dcs|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.dcr|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.dng|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.drf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.eip|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.erf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.fff|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.gpr|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.iiq|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.k25|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.kdc|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.mdc|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.mef|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.mos|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.mrw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.nef|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.nrw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.obm|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.orf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.pef|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.ptx|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.pxn|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.r3d|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.raf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.raw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.rwl|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.rw2|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.rwz|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.sr2|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.srf|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.srw|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;][.x3f|Adobe Photoshop|C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe|&quot;&lt;file&gt;&quot;]" />
      <Item key="AllFormats" value="*.avif;*.b64;*.bmp;*.cur;*.cut;*.dds;*.dib;*.emf;*.exif;*.gif;*.heic;*.heif;*.ico;*.jfif;*.jp2;*.jpe;*.jpeg;*.jpg;*.pbm;*.pcx;*.pgm;*.png;*.ppm;*.psb;*.svg;*.tif;*.tiff;*.webp;*.wmf;*.wpg;*.xbm;*.xpm;*.exr;*.hdr;*.psd;*.tga;*.3fr;*.ari;*.arw;*.bay;*.crw;*.cr2;*.cr3;*.cap;*.dcs;*.dcr;*.dng;*.drf;*.eip;*.erf;*.fff;*.gpr;*.iiq;*.k25;*.kdc;*.mdc;*.mef;*.mos;*.mrw;*.nef;*.nrw;*.obm;*.orf;*.pef;*.ptx;*.pxn;*.r3d;*.raf;*.raw;*.rwl;*.rw2;*.rwz;*.sr2;*.srf;*.srw;*.x3f;" />
      <Item key="KeyComboActions" value="LeftRight:PrevNextImage;PageUpDown:PrevNextImage;SpaceBack:PrevNextImage;UpDown:PanUpDown;" />
      <Item key="BackgroundColor" value="#3A3C3D" />
      <Item key="FrmMainWindowBound" value="102;102;1271;539" />
      <Item key="FrmSettingsWindowBound" value="279;114;1050;750" />
      <Item key="FrmExifToolWindowBound" value="280;125;800;600" />
      <Item key="Language" value="Languages" />
      <Item key="Theme" value="Kobe" />
      <Item key="ExifToolCommandArgs" value="" />
      <Item key="IsUseRawThumbnail" value="False" />
      <Item key="IsHideToolbarInFullscreen" value="False" />
      <Item key="IsHideThumbnailBarInFullscreen" value="False" />
      <Item key="SinglePageFormats" value="*.heic;*.heif;*.psd;" />
    </Content>
  </Configuration>
</ImageGlass>
```

before the very last update everything was working fine

**Comment by Zeus64** [comment]
also in the windows event I have :

Application: ImageGlass.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
   at ImageGlass.Program.CheckFirstLaunchConfigs()
   at ImageGlass.Program.Main()


Faulting application name: ImageGlass.exe, version: 8.5.1.22, time stamp: 0x61ed30b9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1466, time stamp: 0xe01c7650
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x3870
Faulting application start time: 0x01d81742e79b4c3c
Faulting application path: C:\Program Files\ImageGlass\ImageGlass.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 351f094c-0bd1-40d4-8be8-6cd8afd22939
Faulting package full name: 
Faulting package-relative application ID: 



Fault bucket 1970919670557453223, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: ImageGlass.exe
P2: 8.5.1.22
P3: 61ed30b9
P4: ImageGlass
P5: 8.5.1.22
P6: 61ed30b9
P7: 1e5
P8: 3f
P9: System.MissingMethodException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREFB6.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF005.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF006.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF013.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF024.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ImageGlass.exe_4c8f49a4d1e359f8e9d2c80c739d052e436ba4c_6edd57f2_baff77e4-3edf-48f8-828f-dde5c8e9d089

Analysis symbol: 
Rechecking for solution: 0
Report Id: 351f094c-0bd1-40d4-8be8-6cd8afd22939
Report Status: 268435456
Hashed bucket: 125bc65e24a0d48efb5a1cff7c682ba7
Cab Guid: 0

**Comment by fire-eggs** [comment]
Thank you for your continued patience, these sorts of issues are rather difficult to diagnose ...

Is it possible the upgrade has installed the 64-bit version of ImageGlass on a 32-bit system? Could you tell us what version and bit-ness of Windows you are running?

>>Does ImageGlass start if executed from the Start Menu
>no, well ImageGlass start (I can see the exe in the taskmanager) but close 

I asked that to see if it was a problem with file associations etc. The Windows Event log shows that it is not the case.

>the only think is that I installed imageGlass in :\Program Files\ImageGlass\

If you want to sanity check that, you can download the portable version, extract it someplace, and try to run it. At this point, I'm pretty certain the portable version won't run either, no matter where it is placed.

> also in the windows event I have :

Thank you for that! IG is trying to start and is attempting to access a version of software which isn't on your system.

I'd start by (re)?-installing the .NET Framework 4.8 using the link I posted in my first reply. Or repair your .NET installation using the [Microsoft .NET Framework Repair Tool](https://support.microsoft.com/en-us/topic/microsoft-net-framework-repair-tool-is-available-942a01e3-5b8b-7abb-c166-c34a2f4b612a).

**Comment by Zeus64** [comment]
> Is it possible the upgrade has installed the 64-bit version of ImageGlass on a 32-bit system? Could you tell us what version and bit-ness of Windows you are running?

I m on windows 10 64 bit. I ran the installer x64 (24.6 MB)

> If you want to sanity check that, you can download the portable version, extract it someplace, and try to run it. At this point, I'm pretty certain the portable version won't run either, no matter where it is placed.

In fact the portable version is not strictly the same as the one in the installer x64. The exe have the exact same version number but they are different for very few bytes (some dll too)

> I'd start by (re)?-installing the .NET Framework 4.8 using the link I posted in my first reply. Or repair your .NET installation using the [Microsoft .NET Framework Repair Tool](https://support.microsoft.com/en-us/topic/microsoft-net-framework-repair-tool-is-available-942a01e3-5b8b-7abb-c166-c34a2f4b612a).

No it's didn't help :( also .net framework was updated to the very last one offered by Microsoft via windows update.

**Comment by fire-eggs** [comment]
> In fact the portable version is not strictly the same as the one in the installer x64. The exe have the exact same version number but they are different for very few bytes (some dll too)

OK, that is concerning.

I did a clean install of IG 8.5.1.22 on Win10-20H2 into C:\Program Files\ImageGlass. I also got a copy of the portable version. Both run with no issues. Using Explorer properties, I see _no_ difference in size between _any_ files in the two versions.

Between this and since a .NET update made no difference, I'm now thinking the upgrade process might have left you with a mix of 8.5.1.22 and older files. If so, it could also explain the error message in Windows Event.

The Imageglass Portable copy may actually run for you.

My next suggested steps would be to either:
a) un-install IG 8.5.1.22; make sure the ImageGlass folder is destroyed; and do a clean install
b) use the portable version

**Comment by Zeus64** [comment]
yes if I replace the content of the directory C:\Program Files\ImageGlass with the one located in ImageGlass_8.5.1.22_x64.zip (portable version) then it's work well! so it's look like the setup didn't update all dll/file in the directory keeping a mix of new and old files :(

**Comment by d2phap** [comment]
Thanks @Zeus64
I will monitor the issue, but I'm glad that you made it's working now.
