### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by Kazserah** [d2phap/ImageGlass#1375]
Windows 10 Pro 1909
ImageGlass_Moon_9.0.1.518_Beta-1_x64

An error occurred trying to start process 'C:\Program Files\ImageGlass Moon\igconfig.json' with working directory 'C:\Program Files\ImageGlass Moon'. No application is associated with the specified file for this operation.

ImageGlass Moon v9.0.1.518
Microsoft Windows NT 10.0.18363.0 64-bit

System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'C:\Program Files\ImageGlass Moon\igconfig.json' with working directory 'C:\Program Files\ImageGlass Moon'. No application is associated with the specified file for this operation.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ImageGlass.FrmMain.IG_Settings()
   at ImageGlass.FrmMain.MnuSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Merapretu** [comment]
Still getting this error. Beta 2 build

**Comment by d2phap** [comment]
v9.0 beta 2 does not support GUI for settings. All it has done is open the `igconfig.json` by the default associated editor. The error is thrown when you don't have any app to open that extension.

Simply, you can just associate `.json` extension to open in MS Notepad.
