### ISSUE TITLE
Crash on launch of 8.8.4.4 after update

### ISSUE THREAD

**Issue by nwesterhausen** [d2phap/ImageGlass#1533]
### System information:
 - Windows OS version: 11 Pro 22H2
 - ImageGlass version: 8.8.4.4

### To Reproduce
1. Update to latest image glass version
2. Open Image glass

### Actual behavior:
When opening image glass after updating, it gives me an unhandled exception error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<System.String> ImageGlass.Settings.Configs.get_DisabledMenus()'.
   at ImageGlass.frmMain.LoadMenusState()
   at ImageGlass.frmMain.LoadConfig(Boolean isLoadUI, Boolean isLoadOthers)
   at ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ImageGlass.frmMain.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 8.8.4.4
    Win32 Version: 8.8.4.4
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.exe
----------------------------------------
ImageGlass.Base
    Assembly Version: 1.8.0.0
    Win32 Version: 1.8.0.0
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.Base.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Settings
    Assembly Version: 8.7.0.0
    Win32 Version: 8.7.0.0
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.Settings.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 8.7.8493.42595
    Win32 Version: 8.7.8493.42595
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Heart
    Assembly Version: 8.8.0.0
    Win32 Version: 8.8.0.0
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.Heart.DLL
----------------------------------------
ImageGlass.UI
    Assembly Version: 8.7.8493.42595
    Win32 Version: 8.7.8493.42595
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.UI.DLL
----------------------------------------
Magick.NET-Q16-HDRI-OpenMP-x64
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/Magick.NET-Q16-HDRI-OpenMP-x64.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Magick.NET.Core
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/Magick.NET.Core.DLL
----------------------------------------
Magick.NET.SystemDrawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/Magick.NET.SystemDrawing.DLL
----------------------------------------
FileWatcherEx
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/FileWatcherEx.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 8.6.8493.42595
    Win32 Version: 8.6.8493.42595
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.9
    Win32 Version: 11.0.0.9
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
ImageGlass.Services
    Assembly Version: 8.7.8493.42595
    Win32 Version: 8.7.8493.42595
    CodeBase: file:///C:/Users/nwest/AppData/Local/Programs/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

### Expected behavior:
Opens without an exception.

### Screenshots:
Would just be screenshot of the error..

### Additional context:
I did search the repo & issues for "DisabledMenus" to try and find anyone else who posted the error or mentioned it. Saw #1498 and tried adding a key to my config (igconfig.xml) with the "DisabledMenus" key and an empty value, and also with the value from that issue. The same exception happens on launch.

**Comment by d2phap** [comment]
You can use "Repair" to fix the old dll cache.
https://github.com/d2phap/ImageGlass/issues/1525#issuecomment-1489572306
