### ISSUE TITLE
Windows Server 2016 - Interface is not supported - System.ComponentModel.Win32Exception (0x80004002)

### ISSUE THREAD

**Issue by TheButcher200** [d2phap/ImageGlass#1777]
### System information:
 - Windows OS version: Windows Server 2016
 - ImageGlass version: v9.0.8.1208

### To Reproduce
1. Open ImageGlass, users are now greeted with this error message and cannot use ImageGlass anymore on Win Server 2016 since version 9

Error message:
Version: ImageGlass v9.0.8.1208
Release code: kobe
OS: Microsoft Windows NT 10.0.14393.0 64-bit

----------------------------------------------------
Error:

Interface wordt niet ondersteund
----------------------------------------------------

System.ComponentModel.Win32Exception (0x80004002): Interface wordt niet ondersteund
   at DirectN.DWriteFunctions.DWriteCreateFactory[T](DWRITE_FACTORY_TYPE type)
   at D2Phap.DXControl..ctor()
   at ImageGlass.Viewer.DXCanvas..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Views\DXCanvas.cs:line 1065
   at ImageGlass.FrmMain.InitializeComponent() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\FrmMain.Designer.cs:line 145
   at ImageGlass.FrmMain..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\FrmMain.cs:line 60
   at ImageGlass.Program.RunAppInstances() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 177
   at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 84

**Comment by d2phap** [comment]
Hi @TheButcher200 
Your OS is not supported because IG 9 requires Windows ~version 2004 (build 19041)~ version 1809 (build 17763) while your OS build is 14393.
