### ISSUE TITLE
App crash when using CROP tool on a second monitor with diferent DPI

### ISSUE THREAD

**Issue by npn-npn** [d2phap/ImageGlass#1868]
### System information:
 - Windows OS version: Windows 11 x64 (Microsoft Windows NT 10.0.22631.0 64-bit)
 - ImageGlass version: v9.0.10.201

### To Reproduce
1.  Open and Image on a second monitor (different DPI)
2. Try to select "Crop" tool 
3. ImageGlass crashes (below the reported error) 
4. 

### Additional context:
Version: ImageGlass v9.0.10.201
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.5.0
WebView2 Runtime: 122.0.2365.80
OS: Microsoft Windows NT 10.0.22631.0 64-bit
----------------------------------------------------
Error: Object reference not set to an instance of an object.
----------------------------------------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageGlass.FrmCrop.ApplyTheme(Boolean darkMode, Nullable`1 style) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Tools\FrmCrop.cs:line 65
   at ImageGlass.FrmCrop.OnDpiChanged(DpiChangedEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Tools\FrmCrop.cs:line 95
   at System.Windows.Forms.Form.WmDpiChanged(Message& m)
   at ImageGlass.UI.ModernForm.WndProc(Message& m) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.UI\Forms\ModernForm.cs:line 200
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by alessandro-antonelli** [comment]
Probably a duplicate of #1758 ?

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.3 Beta (v9.2.1.216)](https://github.com/d2phap/ImageGlass/releases/tag/9.2.1.216)
