### ISSUE TITLE
Error details:System.Private.CoreLib: An item with the same key has already been added.

### ISSUE THREAD

**Issue by mewoll** [d2phap/ImageGlass#1892]
### System information:
 - Windows OS version: Windows10
 - ImageGlass version: 9.0.10.201 (64-bit)

### To Reproduce
1. install ImageGlass_9.0.10.201_x64.msi
2. open ImageGlass.exe
3. 
4. 

### Actual behavior:

Unable to view picture

### Screenshots:

![Snipaste_2024-04-23_19-57-55](https://github.com/d2phap/ImageGlass/assets/38155355/87db56c6-7c51-4384-a2cc-9be35fdc20be)
![Snipaste_2024-04-23_19-53-20](https://github.com/d2phap/ImageGlass/assets/38155355/02b59478-2382-4e71-a943-dd04ee0df3b8)
![Snipaste_2024-04-23_19-50-38](https://github.com/d2phap/ImageGlass/assets/38155355/636c112d-25ae-4f63-ab4a-d0e89a2a9667)

### Additional context:

  I rolled back the old version and it was working fine.

All error messages in the second picture:
Version: ImageGlass v9.0.10.201
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.5.0
WebView2 Runtime: 124.0.2478.51
OS: Microsoft Windows NT 10.0.19045.0 64-bit

-------------------------------------------------- --
Error:

An item with the same key has already been added. Key: a26cec36-234c-4950-ae16-e34aace71d0d
-------------------------------------------------- --

System.ArgumentException: An item with the same key has already been added. Key: a26cec36-234c-4950-ae16-e34aace71d0d
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
    at WicNet.WicImagingComponent.<>c__DisplayClass3_0.<LoadAllComponents>b__0(IWICImagingFactory f)
    at DirectN.WICImagingFactory.WithFactory(Action`1 action)
    at WicNet.WicImagingComponent.LoadAllComponents()
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
    at System.Lazy`1.CreateValue()
    at WicNet.WicImagingComponent.FromClsid[T](Guid clsid)
    at WicNet.WicBitmapSource.ConvertTo(Guid pixelFormat, WICBitmapDitherType ditherType, WicPalette palette, Double alphaThresholdPercent, WICBitmapPaletteType paletteTranslate)
    at D2Phap.DXHelper.ToD2D1Bitmap(IComObject`1 dc, WicBitmapSource wicSrc, Nullable`1 bitmapProps)
    at ImageGlass.Viewer.DXCanvas.SetImage(IgImgData imgData, UInt32 frameIndex, Boolean resetZoom, Boolean enableFading, Single initOpacity, Single opacityStep, Boolean isForPreview, Boolean autoAnimate, ImgTransform transforms) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components \ImageGlass.Views\DXCanvas.cs:line 3024
    at ImageGlass.FrmMain.ShowImagePreview(String filePath, CancellationToken token) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\FrmMain.cs:line 1282
    at ImageGlass.FrmMain.HandleImageProgress_Loading(ImageLoadingEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\FrmMain.cs:line 1054
    at ImageGlass.FrmMain.ReportToUIThread(ProgressReporterEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\FrmMain.cs:line 981
    at System.Progress`1.InvokeHandlers(Object state)
    at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by d2phap** [comment]
Duplicated #1842, should be fixed in v9.0.11!
