### ISSUE TITLE
ImageGlass Won't Open After a Recent Windows 10 Update

### ISSUE THREAD

**Issue by SolomonDread** [d2phap/ImageGlass#1915]
### System information
- Windows OS version: Windows10 22H2
- ImageGlass version: 9.0.11.502 (64-bit)
- ImageGlass release: Classic

### To Reproduce
1. Install the KB5037768, KB5038285, and KB5038351 Windows Updates.
2. Try Opening ImageGlass App.

### Actual behavior
ImageGlass won't open, the only thing that happened is that I can only hear the Windows error/warning sound in the background, but that's it. No message or anything.

### Expected behavior
ImageGlass should open as usual, because I was using it right before the update. ImageGlass I used was up-to-date, so I haven't done anything to it, not even touching the config before updating my Windows.

### Screenshots / Video / Sample image file
![WindowsUpdatesHistory](https://github.com/d2phap/ImageGlass/assets/99858862/0bcba1a1-7075-458e-8b40-a8001b0f1ded)

KB5034441 won't update is a known issue within the Windows community, it haven't worked for months, but ImageGlass worked even back then.

### Additional context
In an attempt to fix the problem myself, I tried the following:

Updating .NET Desktop Runtime 9 (64-bit).
Updating WebView2 Runtime (64-bit).
Restart the device.
Try running ImageGlass as administrator.
Reinstall ImageGlass, and clean out any folders in the Local and Roaming directory as well.
Downgrading ImageGlass to 9.0.10.201.
Check if other image viewing apps work (found no problems with other apps).

Also, after the reinstall, since the app still wouldn't start, it doesn't produce the igconfig file or anything else in the folders in Local and Roaming.

**Comment by d2phap** [comment]
I tried to reproduce this in VirtualBox, I have installed all the updates but could not find KB5038351.
ImageGlass works normally.

![1](https://github.com/d2phap/ImageGlass/assets/3154213/c31392f2-42ab-42c4-a143-1032d918ad3e)


Can you check the "Event Viewer" and apply some filters to find the error?

![image](https://github.com/d2phap/ImageGlass/assets/3154213/1df4a76b-f638-41c1-a770-27c024308780)

**Comment by SolomonDread** [comment]
Thanks, found the error, here are the screenshots. If you want a log in other format, I'll get them for you. There are two logs. 
________________________________________________________________________________________________________________________________
![Error1](https://github.com/d2phap/ImageGlass/assets/99858862/9b3c988e-f024-4b7d-92c9-147a9500b871)
________________________________________________________________________________________________________________________________
![Error2Part1](https://github.com/d2phap/ImageGlass/assets/99858862/fa47a3ba-7d6c-4d34-9f88-91d2ed0f62a6)
![Error2Part2](https://github.com/d2phap/ImageGlass/assets/99858862/f6a455f5-0b15-46f7-b3d8-5ca95982243d)
________________________________________________________________________________________________________________________________
Faulting application name: ImageGlass.exe, version: 9.0.11.502, time stamp: 0x65a80000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4355, time stamp: 0xd7762934
Exception code: 0xe0434352
Fault offset: 0x000000000002ba99
Faulting process id: 0x7f8
Faulting application start time: 0x01daa7894329e920
Faulting application path: C:\Program Files\ImageGlass\ImageGlass.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 
Faulting package full name: 
Faulting package-relative application ID: 
________________________________________________________________________________________________________________________________

Application: ImageGlass.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.VisualStyles.VisualStyleRenderer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.SystemEvents, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Win32.SystemEvents, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Windows.Forms.VisualStyles.VisualStyleRenderer..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Forms.VisualStyles.VisualStyleRenderer.get_IsSupported()
   at System.Windows.Forms.ButtonInternal.ButtonStandardAdapter.Layout(PaintEventArgs e)
   at System.Windows.Forms.ButtonInternal.ButtonBaseAdapter.GetPreferredSizeCore(Size proposedSize)
   at System.Windows.Forms.ButtonBase.GetPreferredSizeCore(Size proposedConstraints)
   at System.Windows.Forms.Button.GetPreferredSizeCore(Size proposedConstraints)
   at System.Windows.Forms.Control.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.ButtonBase.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.Layout.TableLayout.InflateColumns(ContainerInfo containerInfo, Size proposedConstraints, Boolean measureOnly)
   at System.Windows.Forms.Layout.TableLayout.ApplyStyles(ContainerInfo containerInfo, Size proposedConstraints, Boolean measureOnly)
   at System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.TableLayoutPanel.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at ImageGlass.Settings.DialogForm.AppendActionBar() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\DialogForm.cs:line 235
   at ImageGlass.Settings.DialogForm..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\DialogForm.cs:line 140
   at ImageGlass.Settings.Popup..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\Popup.cs:line 399
   at ImageGlass.Settings.Popup.ShowDialog(String description, String title, String heading, String details, String note, Nullable`1 noteStatusType, PopupButton buttons, Nullable`1 icon, Image thumbnail, String optionText, Boolean topMost, Form formOwner) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\Popup.cs:line 648
   at ImageGlass.Settings.Config.ShowError(Form formOwner, String description, String title, String heading, String details, String note, Nullable`1 icon, Image thumbnail, PopupButton buttons, String optionText) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 1999
   at ImageGlass.Settings.Config.HandleException(Exception ex) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 2060
   at ImageGlass.Program.<>c.<Main>b__2_0(Object sender, UnhandledExceptionEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 52

**Comment by SolomonDread** [comment]
In the meantime, I'll try uninstalling KB5038351 the next time I got back to my main PC as well. My laptop has the same updates, except KB5038351, and ImageGlass works fine on that device.

**Comment by SolomonDread** [comment]
Update: No joy, KB5038351 can't be uninstalled.

**Comment by d2phap** [comment]
Searching for error `0xe0434352`, can you follow this instruction if it work?

https://answers.microsoft.com/en-us/windows/forum/all/the-exception-unknown-software-exception/f1404ce4-cdbe-4758-aa19-bad55fcc099c

**Comment by SolomonDread** [comment]
Good news, I found the culprit after multiple trial-and-error attempts. It's the .NET SDK 8.0.300, which had been broken for unknown reason. I repaired it and installed ImageGlass again, and it works! And yes, I did try to look up the 0xe0434352 fixes before, but none of the solutions worked. But thanks for the quick and helpful replies! I'm happy I can use ImageGlass again!

**Comment by d2phap** [comment]
Great!
