### ISSUE TITLE
ERROR: Method not found: 'Single ImageGlass.Settings.Config.get_QuickSetupVersion0'.

### ISSUE THREAD

**Issue by traviss64** [d2phap/ImageGlass#1969]
### System information
- Windows OS version: 11 (22631.3880)
- ImageGlass version: v9.1.8.723
- ImageGlass release: Classic // Github

### To Reproduce
1. Open any image
2. Error pop up window

### Expected behavior

```
Version: ImageGlass v9.1.8.723
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.10.0
WebView2 Runtime: 126.0.2592.113
OS: Microsoft Windows NT 10.0.22631.0 64-bit

----------------------------------------------------
Error:

Method not found: 'Single ImageGlass.Settings.Config.get_QuickSetupVersion()'.
----------------------------------------------------

System.MissingMethodException: Method not found: 'Single ImageGlass.Settings.Config.get_QuickSetupVersion()'.
   at ImageGlass.Program.CheckAndRunQuickSetup() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 115
   at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 92
```

![image](https://github.com/user-attachments/assets/d25af6d7-be8b-4e27-874c-ab6f31776750)

**Comment by d2phap** [comment]
@traviss64 Can you send me your `igconfig.json` file (located in `%LocalAppData%/ImageGlass` folder)?

Is this your first time install ImageGlass or you upgrade from previous version?

**Comment by traviss64** [comment]
> @traviss64 Can you send me your `igconfig.json` file (located in ImageGlass startup folder)?
> 
> Is this your first time install ImageGlass or you upgrade from previous version?

I upgraded from the previous version

**Comment by d2phap** [comment]
Can you send me your `igconfig.json` file (located in `%LocalAppData%/ImageGlass` folder)?

You can try deleting the `igconfig.json` file if it helps

**Comment by traviss64** [comment]
> Can you send me your `igconfig.json` file (located in `%LocalAppData%/ImageGlass` folder)?

I uninstalled the software and deleted it's files so I could installed the previous version which is working fine

> You can try deleting the `igconfig.json` file if it helps

I tried this before uninstalling the version and got the same error

**Comment by sjx-github** [comment]
I also encountered the same problem while upgrading to a new version. After trying, I first used ImageGlass_9.1.8.723_x64.exe to uninstall the current version, but found that the files in the installation directory were not deleted after the program ended, so I deleted them manually. All files in the installation directory C:\Program Files\ImageGlass, run ImageGlass_9.1.8.723_x64.exe again to install the latest version, this time no error is reported, everything is normal, the above are my solution steps, I hope it will be helpful to you

**Comment by FailSafeNow** [comment]
I got the same error. Removing all the files from the program directory and reinstalling fixed it... but I kept the old files for testing.

ImageGlass.Base.dll - If I put the old version back, it doesn't launch. Nothing happens. I don't even get the crash message.

ImageGlass.Settings.dll - If I put back the old version, THEN I get the error.

So these two files cause problems. The others seem to be fine.

**Comment by Garywoo** [comment]
I'm also experiencing the error. 

Here's my [igconfig.json](https://github.com/user-attachments/files/16420889/igconfig.json)

**Comment by Greentrees24** [comment]
I had a similar error (unhandled exception). Found two installs for Image Glass, one old one new. Uninstalled both, reinstalled latest version and now all good.

**Comment by FailSafeNow** [comment]
I'm telling you, igconfig won't give you anything useful. You gotta remove ImageGlass.Base.dll and ImageGlass.Settings.dll, then run the installer.

**Comment by Tutul-** [comment]
Got the same issue after an upgrade. Repair doesn't work so I had to uninstall/reinstall
(upgrade without the Windows store)

Also, found out that the previous version was still installed too... Look like a problem in the installation/upgrade process

**Comment by d2phap** [comment]
Does not seem happen to the installer of the recent versions any more. I will close this.
