### ISSUE TITLE
Turn off the second monitor causes Win32Exception (0x8899000C)

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#1970]
### System information
- Windows OS version:  10.0.22631.3737
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic

### To Reproduce
1. Prepare a laptop and a second monitor.
2. Set the behavior of closing lid to "turn off screen"
3. Open a image on the second monitor.
4. Close laptop lid and turn off the second monitor.
5. Open lid and turn on the second monitor.

### Actual behavior
Image opened will be:
![image](https://github.com/user-attachments/assets/790ac2d7-399f-4552-9675-5f448cdd5fb3)

with error:

```
Version: ImageGlass v9.1.8.723
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.10.0
WebView2 Runtime: 126.0.2592.113
OS: Microsoft Windows NT 10.0.22631.0 64-bit

----------------------------------------------------
Error:

There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x8899000C): There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
   at DirectN.HRESULT.ThrowOnErrorExcept(IEnumerable`1 exceptedValues, Boolean throwOnError)
   at DirectN.ID2D1DeviceContextExtensions.EndDraw(ID2D1DeviceContext context)
   at D2Phap.DXControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

### Expected behavior
Display the image.

### Additional context
I thought this bug started from recent versions because I often do the same thing but this error did not occur in the past.

**Comment by sebastienlemieux277** [comment]
Version: ImageGlass v9.1.8.723
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.10.0
WebView2 Runtime: 129.0.2792.65
OS: Microsoft Windows NT 10.0.20348.0 64-bit

----------------------------------------------------
Error:

There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x8899000C): There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
   at DirectN.HRESULT.ThrowOnErrorExcept(IEnumerable`1 exceptedValues, Boolean throwOnError)
   at DirectN.ID2D1DeviceContextExtensions.EndDraw(ID2D1DeviceContext context)
   at D2Phap.DXControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

We have the same error message on Terminal Server. If we are closing our connections and connecting back to them, we can replicate the issue. The issue started since we updated to the last version.

**Comment by d2phap** [comment]
@TheCGDF 
Do you mind to test this build if it's fixed?
https://drive.google.com/file/d/12ibBt7giHU1ZDC56yX1jVqz8lYMF7w0Q/view?usp=sharing

**Comment by TheCGDF** [comment]
> @TheCGDF Do you mind to test this build if it's fixed? https://drive.google.com/file/d/12ibBt7giHU1ZDC56yX1jVqz8lYMF7w0Q/view?usp=sharing

Not fixed.

```
Version: ImageGlass v9.1.8.1104
Release code: kobe
Magick.NET: Magick.NET Q8-OpenMP x64 net8.0 14.2.0
WebView2 Runtime: 131.0.2903.70
OS: Microsoft Windows NT 10.0.22631.0 64-bit

----------------------------------------------------
Error:

There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x8899000C): There has been a presentation error that may be recoverable. The caller needs to recreate, rerender the entire frame, and reattempt present.
   at DirectN.HRESULT.ThrowOnErrorExcept(IEnumerable`1 exceptedValues, Boolean throwOnError)
   at DirectN.HRESULT.ThrowOnError(Boolean throwOnError)
   at DirectN.ID2D1DeviceContextExtensions.EndDraw(ID2D1DeviceContext context)
   at DirectN.ID2D1DeviceContextExtensions.EndDraw(IComObject`1 context)
   at D2Phap.DXControl.DXCanvas.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.DXCanvas.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by d2phap** [comment]
Removed the second limit in [ImageGlass 9.2.0.1208 - Maroon 4](https://github.com/d2phap/ImageGlass/releases/tag/9.2.0.1208). The slideshow time may not be accurate for < 1 second

**Comment by TheCGDF** [comment]
@d2phap I updated to 9.2.0.1208 but still not fixed.
I think it is not related to slideshow.

**Comment by TheCGDF** [comment]
I think you replied & closed wrong issue. I guess the issue you wanted to replay and close is https://github.com/d2phap/ImageGlass/issues/2047

**Comment by d2phap** [comment]
Oops I put my comment in a wrong ticket 🥹

**Comment by d2phap** [comment]
This should be no longer an issue for [ImageGlass 10.0.4.819](https://github.com/d2phap/ImageGlass/releases/tag/10.0.4.819)
