### ISSUE TITLE
Could not find a part of the path | Pressing 'C'

### ISSUE THREAD

**Issue by laniakeadev** [d2phap/ImageGlass#2004]
### System information
- Windows OS version: Windows 10 64
- ImageGlass version: 9.0.5.726
- ImageGlass release: Store / Classic? moon

### To Reproduce
1. Open photo
2. Press 'C'
3. Enjoy

`Error:

Could not find a part of the path 'C:\Users\Omega\AppData\Local\ImageGlass\Icons\Setting.svg'.
----------------------------------------------------

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\AppData\Local\ImageGlass\Icons\Setting.svg'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at ImageGlass.Base.Photoing.Codecs.PhotoCodec.ReadSvgWithMagick(String svgFilePath, Boolean darkMode, Nullable`1 width, Nullable`1 height) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.Base\Photoing\Codecs\PhotoCodec.cs:line 323
   at ImageGlass.Base.BHelper.ToGdiPlusBitmapFromSvg(String svgFilePath, Boolean darkMode, Nullable`1 width, Nullable`1 height) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.Base\BHelper\Photoing.cs:line 340
   at ImageGlass.UI.ModernButton.UpdateSvgImage(Boolean darkMode) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.UI\Buttons\ModernButton.cs:line 590
   at ImageGlass.UI.ModernButton.set_SvgIcon(IconName value) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.UI\Buttons\ModernButton.cs:line 111
   at ImageGlass.FrmCrop.InitializeComponent() in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\Tools\FrmCrop.Designer.cs:line 137
   at ImageGlass.FrmCrop..ctor(Form owner) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\Tools\FrmCrop.cs:line 47
   at ImageGlass.FrmMain.IG_ToggleCropTool(Nullable`1 visible) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\FrmMain\FrmMain.IGMethods.cs:line 2914
   at ImageGlass.FrmMain.MnuCropTool_Click(Object sender, EventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\FrmMain.cs:line 2280
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at ImageGlass.FrmMain.<>c__DisplayClass15_0.<FrmMain_KeyDown>g__CheckMenuShortcut|0(ToolStripMenuItem mnu) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\FrmMain.cs:line 191
   at ImageGlass.FrmMain.<>c__DisplayClass15_0.<FrmMain_KeyDown>g__CheckMenuShortcut|0(ToolStripMenuItem mnu) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\FrmMain.cs:line 199
   at ImageGlass.FrmMain.FrmMain_KeyDown(Object sender, KeyEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\ImageGlass\FrmMain.cs:line 209
   at ImageGlass.UI.ModernForm.OnKeyDown(KeyEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.UI\Forms\ModernForm.cs:line 295
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ImageGlass.UI.ModernForm.WndProc(Message& m) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.UI\Forms\ModernForm.cs:line 201
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

Content of the folder:
![image](https://github.com/user-attachments/assets/2dacb0a6-983d-4135-a7c4-fa2de4e530e3)

**Comment by d2phap** [comment]
You're using beta release of v9, please update to the latest version
