### ISSUE TITLE
Unable to run version 9.2.0.1208 on windows arm64

### ISSUE THREAD

**Issue by BohusSabol** [d2phap/ImageGlass#2055]
### System information
- Windows OS version: Windows 11 24H2 (OS Build 26100.2454) on Snapdragon(R) X Elite
- ImageGlass version: 9.2.0.1208 arm64 version
- ImageGlass release: Classic

### To Reproduce
1. unzip file
2. run app
3. 
4. 

### Actual behavior
App crash

### Expected behavior
App run

### Additional context
Application Event log:
Application: ImageGlass.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Magick.NET-Q16-HDRI-OpenMP-x64, Version=14.2.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'. The system cannot find the file specified.
File name: 'Magick.NET-Q16-HDRI-OpenMP-x64, Version=14.2.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'
   at ImageGlass.Base.BHelper.ToGdiPlusBitmapFromSvg(String svgFilePath, Boolean darkMode, Nullable`1 width, Nullable`1 height)
   at ImageGlass.UI.ModernButton.UpdateSvgImage(Boolean darkMode) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.UI\Buttons\ModernButton.cs:line 592
   at ImageGlass.UI.ModernButton.set_DarkMode(Boolean value) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.UI\Buttons\ModernButton.cs:line 69
   at ImageGlass.Settings.DialogForm.AppendActionBar() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\DialogForm.cs:line 185
   at ImageGlass.Settings.DialogForm..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\DialogForm.cs:line 140
   at ImageGlass.Settings.Popup..ctor() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\Popup.cs:line 399
   at ImageGlass.Settings.Popup.ShowDialog(String description, String title, String heading, String details, String note, Nullable`1 noteStatusType, PopupButton buttons, Nullable`1 icon, Image thumbnail, String optionText, Boolean topMost, Form formOwner) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Forms\Popup.cs:line 648
   at ImageGlass.Settings.Config.ShowError(Form formOwner, String description, String title, String heading, String details, String note, Nullable`1 icon, Image thumbnail, PopupButton buttons, String optionText) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 2037
   at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 83

**Comment by d2phap** [comment]
Thanks, I just removed the ARM64 release. I will add back later

**Comment by BohusSabol** [comment]
If you need help with testing, let me know.

**Comment by d2phap** [comment]
@BohusSabol I will create a new ARM64 build next 2 weeks. Currently I don't have Windows laptop.

**Comment by d2phap** [comment]
@BohusSabol Can you help to check if this [ImageGlass_9.2.0.1208_arm64.zip](https://github.com/d2phap/ImageGlass/releases/download/9.2.0.1208/ImageGlass_9.2.0.1208_arm64.zip) works?

I'm not sure why IG refers to x64 version if Magick.NET even though the DLL file is arm64

**Comment by BohusSabol** [comment]
Yes, this version works.
![Screenshot 2025-01-11 190728](https://github.com/user-attachments/assets/fc33077d-f9c4-4f31-83a4-599c41cf4a0b)

If you need help with testing in the future, ping me.
