### ISSUE TITLE
The Color Picker and Crop Image tool cannot be launched on the second display

### ISSUE THREAD

**Issue by sk-ys** [d2phap/ImageGlass#2063]
### System information
- Windows OS version: Windows 11 Pro 24H2
- ImageGlass version: 9.2.0.1208(64-bit)
- ImageGlass release: Store / Classic? Classic

### To Reproduce
1. Launch ImageGlass on the second display.
2. Launch the Color Picker or Crop Image tool.

Note: The issue cannot be reproduced if the application is launched on the main display and then moved to the second display.

### Actual behavior
![image](https://github.com/user-attachments/assets/8eafc07a-4405-4f26-a17e-43cb0a09fe63)

#### Error message
```
Version: ImageGlass v9.2.0.1208
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 net8.0 14.2.0
WebView2 Runtime: 131.0.2903.99
OS: Microsoft Windows NT 10.0.26100.0 64-bit

----------------------------------------------------
Error:

Object reference not set to an instance of an object.
----------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageGlass.FrmCrop.ApplyTheme(Boolean darkMode, Nullable`1 style) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Tools\FrmCrop.cs:line 65
   at ImageGlass.FrmCrop.OnDpiChanged(DpiChangedEventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Tools\FrmCrop.cs:line 96
   at System.Windows.Forms.Form.WmDpiChanged(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ImageGlass.UI.ModernForm.WndProc(Message& m) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.UI\Forms\ModernForm.cs:line 221
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   ```

### Expected behavior
![image](https://github.com/user-attachments/assets/50c43320-069d-42cd-812b-4590f997c041)

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.3 Beta (v9.2.1.216)](https://github.com/d2phap/ImageGlass/releases/tag/9.2.1.216)
