### ISSUE TITLE
Unhandled exception - Index was out of range

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#225]
### Actual behavior:

```
************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at ImageGlass.Core.ImgMan.Unload(Int32 i)
   at ImageGlass.frmMain.sysWatch_Changed(Object sender, FileSystemEventArgs e)
```

### Steps to reproduce:
1. Make a folder with two or more jpg files
2. Open one of the jpg files with ImageGlass
3. Move the files to a different folder
4. Click in the ImageGlass window

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 8

**Comment by d2phap** [comment]
Thanks @Keith94 
This is similar to #193
