### ISSUE TITLE
Error Occurs when Uninstalling Theme

### ISSUE THREAD

**Issue by chenrylee** [d2phap/ImageGlass#279]
I installed a theme, and then tried to uninstall it (via extensions manager). This error occurred:
> OS: Windows 10 Pro 1709 x64
```csharp
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ThemeConfig.ctlMain.btnUninstall_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 4.5.11.27
    Win32 Version: 4.5.11.27
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 4.5.6539.23370
    Win32 Version: 4.5.6539.23370
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 4.5.6538.39036
    Win32 Version: 4.5.6538.39036
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 4.5.6538.22559
    Win32 Version: 4.5.6538.22559
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Theme
    Assembly Version: 4.5.6539.23371
    Win32 Version: 4.5.6539.23371
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 4.5.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.3
    Win32 Version: 11.0.0.3
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.7.900
    CodeBase: file:///D:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
ImageGlass.Plugins
    Assembly Version: 1.1.6538.22559
    Win32 Version: 1.1.6538.22559
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Plugins.DLL
----------------------------------------
ThemeConfig
    Assembly Version: 4.1.6483.21752
    Win32 Version: 4.5
    CodeBase: file:///D:/Program%20Files/ImageGlass/Plugins/ThemeConfig.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by d2phap** [comment]
Hi @chenrylee 

Can you manually uninstall it by going to this folder `%appdata%\ImageGlass\Themes` and delete the theme.

I have tried installing and uninstalling as you said but it still works fine for me.

**Comment by d2phap** [comment]
Won't fix this because in the next version, Extension Manager feature will be removed.
The Theme Configs will be moved to Settings dialog for better managing

**Comment by chenrylee** [comment]
Thank you, @d2phap .
Indeed I already removed the theme as you said before I posted this issue.
