### ISSUE TITLE
Could not find a part of the path '%appdata%\ImageGlass\Temp'.

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#323]
### Steps to reproduce:
1. Open latest version of ImageGlass Moon
2. Open menu and click "A new version is available"
3. Open a second window of ImageGlass.exe
4. Right-click ImageGlass taskbar icon and choose 'Close all Windows' (2)

### System info:
- ImageGlass version: 5.0.4.14
- OS version: Windows 10 1709

### Other info:
```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\NAME\AppData\Roaming\ImageGlass\Temp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at ImageGlass.frmMain.frmMain_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at ImageGlass.frmMain.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 5.0.4.14
    Win32 Version: 5.0.4.14
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 4.5.6681.31963
    Win32 Version: 4.5.6681.31963
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 4.5.6680.21166
    Win32 Version: 4.5.6680.21166
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 4.5.6681.31935
    Win32 Version: 4.5.6681.31935
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Theme
    Assembly Version: 4.5.6681.31963
    Win32 Version: 4.5.6681.31963
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 4.5.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.3
    Win32 Version: 11.0.0.3
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.4.2.0
    Win32 Version: 7.4.2.0
    CodeBase: file:///C:/Program%20Files/ImageGlass%20Moon/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by d2phap** [comment]
thanks @Keith94 
I just fixed it in `develop` branch and will upload to server soon
