### ISSUE TITLE
Problems with Desktop Background: Mapped drive

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#326]
### Expected behavior:
"Set as Desktop Background" should work, and appear immediately, for any image visible in ImageGlass.

### Actual behavior:
When viewing images using a mounted drive, "Set as Desktop Background" does nothing.

### Steps to reproduce:
1. Insure you have a mapped drive. This can be done in the command prompt window to a local
drive, e.g. `net use x: \\localhost\e` or remote `net use x: \\remote\e`.
2. Run image glass, opening an image folder using the mapped drive.
3. Right-click on the image in Image Glass, select "set as desktop background".
4. Acknowledge allowing igtasks.exe to run as admin.

### System info:
- ImageGlass version: 5.0.4.18 (Moon)
- OS version: Windows 7 Pro

### Other info:
Logged in as a user, **not** administrator.
If the remote drive is accessed via a network path (e.g. in ImageGlass, open files from the network path `\\remote\e` then 'Set as Desktop Background" almost works (see next issue).

To diagnose this, I added debugging log to igtasks. A System.Net.WebException is thrown as follows. Note that the path does in fact exist, the problem is (likely) to be due to igtasks being run as admin, which does *not* know about the mapped drive!

4/18/2018 2:45:31 PM:DesktopWallapaper.cs-Set(Uri,Style):Could not find a part of the path 'V:\downloads\250908.jpg'.
System.Net.WebException: Could not find a part of the path 'V:\downloads\250908.jpg'. ---> System.Net.WebException: Could not find a part of the path 'V:\downloads\250908.jpg'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'V:\downloads\250908.jpg'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.OpenRead(Uri address)
   at ImageGlass.Library.Image.DesktopWallapaper.Set(Uri uri, Style style) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\Components\ImageGlass.Library\Image\DesktopWallapaper.cs:line 80

**Comment by fire-eggs** [comment]
A suggested solution:
Setting desktop background does not require admin privs. Perhaps "Set as Desktop Background" could be moved to igcmds.exe instead?

Or the logic for "Set as desktop Background" could be moved from igtasks into ImageGlass proper?

**Comment by fire-eggs** [comment]
Problem also observed on Windows 10.
