### ISSUE TITLE
Exception from ColorPicker

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#328]
### Expected behavior:
No crash/exception.

### Actual behavior:
When opening a new image folder, I'm periodically receiving exceptions (crash) from the ColorPicker.

### Steps to reproduce:
1. Run image glass. Insure the color picker is visible.
2. Open a new image (pref. in a folder with images).
3. Shortly after clicking 'Open' in the dialog, be moving the mouse across ImageGlass.

Difficult to repeat.

### System info:
- ImageGlass version: 5.0.4.18 (Moon)
- OS version: Windows 10

### Other info:

I'm running a locally built 5.0.4.18 with logging of exceptions caught at the application level (i.e. handling uncaught exceptions).

Here is an example of the crash details I get for this bug:

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ImageGlass.frmColorPicker._imgBox_MouseMove(Object sender, MouseEventArgs e) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmColorPicker.cs:line 300
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at ImageGlass.ImageBox.OnMouseMove(MouseEventArgs e) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\Components\ImageGlass.ImageBox\ImageBox.cs:line 927
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ImageGlass.frmMain.NextPic(Int32 step, Boolean isKeepZoomRatio, Boolean isSkippingCache) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 390
   at ImageGlass.frmMain.NextPic(Int32 step) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 369
   at ImageGlass.frmMain.Prepare(String path) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 233
   at ImageGlass.frmMain.OpenFile() in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 158
   at ImageGlass.frmMain.mnuMainOpenFile_Click(Object sender, EventArgs e) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 2498
   at ImageGlass.frmMain.btnOpen_Click(Object sender, EventArgs e) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\frmMain.cs:line 2284
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ImageGlass.Program.Main(String[] argv) in E:\projects\ImageGlass\ImageGlassMoon5_0_4_18\Source\ImageGlass\Program.cs:line 108

**Comment by fire-eggs** [comment]
Issue 330 is the bad layout of the toolbar settings tab on Windows 7.

I've dug into this, and understand the cause, but I'm not sure how you'd
prefer to fix it.

The reason for the problem is the use of a fixed split container, combined
with you (apparently) designing with your fonts set to 150%. On Windows 7,
users with fonts set to 100% or 125% see a bad layout, but at 150% the
layout works fine. The listviews don't seem to be autoscaling as desired.

If I let Visual Studio designer re-jigger the form design with fonts at
100%, the layout works, but all the rest of the settings tabs are badly
laid out and sized.

These are the possible solutions I see:
1. Use a table layout instead of split container. A quick & dirty test
suggests the table layout works for both Win 7 & 10. There was a reason why
you switched to a split container, so I fear a regression of some sort.
2. Drop the listviews and use owner-drawn listboxes. The split container
will still need to be replaced, but the problems from maximizing the dialog
should be fixed.
3. Re-design the settings dialog at 100% fonts. More work than either of us
want to tackle?
4. Drop the feature for 5.0 pending a solution.

Other ideas appreciated!

I also have to apologize - I intended this to be a helpful addition, not a
source of bugs and frustration!

Kevin​

**Comment by d2phap** [comment]
Hi Kevin, 
Really appreciate your help because of my limited knowledge and time.
If you're interested in developing ImageGlass, I would like to invite /add you as collaborators? There is no timeline in developing at all :)

Back to the ***toolbar settings*** issue, I will just leave it first as it is not a big issue. Because I gonna release the new version in the early of May, I need to close the development by May 1st to prepare for language translation.

Phap

**Comment by fire-eggs** [comment]
Hey, Phap!

>Really appreciate your help because of my limited knowledge and time.
>If you're interested in developing ImageGlass, I would like to invite /add
you as >collaborators? There is no timeline in developing at all :)
If my contributions have been at all helpful, then yes, being a
collaborator would be great! You'll need to give me some guidance for goals
and milestones, etc, but that conversation should probably wait until the
V5.0 chaos has settled.

>Back to the *toolbar settings* issue, I will just leave it first as it is
not a big issue. >Because I gonna release the new version in the early of
May, I need to close the >development by May 1st to prepare for language
translation.
I didn't know what your timeline was for the V5.0 release. Given the short
timeframe, yeah, it makes sense to not fix the issue now. I'll add a
comment to the issue, and poke at on the side.

My thanks, and looking forward to future projects!
Kevin

**Comment by d2phap** [comment]
Thanks @fire-eggs !
I just invited you, please accept!

For development, just do what you can do when you are happy and have free time.
That's how I am doing right now 😄
