### ISSUE TITLE
IndexOutOfRangeException when opening image from Skype

### ISSUE THREAD

**Issue by manjabes** [d2phap/ImageGlass#376]
### System information:
 - Windows OS version: 
Windows 10 1803

 - ImageGlass version: 
5.1.5.20

### Describe the bug:
When opening an image that was sent in a Skype conversation, the following exception usually (but not always) occurs:

```
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ImageGlass.ImageListView.ImageListViewCacheMetadata.RunWorker(CacheRequest item)
   at ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.InsertInternal(Int32 index, ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   at ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.Add(ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   at ImageGlass.frmMain.LoadThumbnails()
   at ImageGlass.frmMain.Prepare(String path)
   at ImageGlass.frmMain.LoadFromParams(String[] args)
   at ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ImageGlass.frmMain.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
### Expected behavior:
Displaying the image

### Additional context:
This seems the same as #341, but in that case there were over 3000 images in the folder. In my Skype image cache there are currently a little over 2100. This bug was in an earlier version of ImageGlass, then it was fixed and then it reappeared in a later one.

FWIW, the rest of the exception message, detailing loaded assemblies:

```
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 5.1.5.20
    Win32 Version: 5.1.5.20
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 5.0.6714.38452
    Win32 Version: 5.0.6714.38452
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 5.0.6714.38452
    Win32 Version: 5.0.6714.38452
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 5.0.6714.38452
    Win32 Version: 5.0.6714.38452
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Theme
    Assembly Version: 5.0.6714.39097
    Win32 Version: 5.0.6714.39097
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 4.5.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.3
    Win32 Version: 11.0.0.3
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.4.5.0
    Win32 Version: 7.4.5.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
```

**Comment by d2phap** [comment]
Can you try the v5.1.7.2 here: https://imageglass.org/moon?

**Comment by manjabes** [comment]
Looks like ver 5.1.7.2 handles that case better. During my quick 5-minute test, it has not yet crashed with this exception any more.

**Comment by d2phap** [comment]
thanks @manjabes !

**Comment by d2phap** [comment]
Updated the File Watcher engine, fixed a lot of issues with realtime updating
https://imageglass.org/moon
