### ISSUE TITLE
Error reading the C:\Users\User\Application Data directory

### ISSUE THREAD

**Issue by motaz-alnuweiri** [d2phap/ImageGlass#405]
### System information:
 - Windows OS version: 10 Build 1803
 - ImageGlass version: 5.5.7.26

### Describe the bug:
When I open any images in my user folder I get this error message

> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
> 
> Error reading the C:\Users\User\Application Data directory.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Error reading the C:\Users\User\Application Data directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at FileWatcherEx.FileWatcher.MakeWatcher(String path)
   at FileWatcherEx.FileWatcher.Create(String path, Action`1 onEvent, Action`1 onError)
   at FileWatcherEx.FileWatcherEx.Start()
   at ImageGlass.frmMain.Prepare(String path)
   at ImageGlass.frmMain.LoadFromParams(String[] args)
   at ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ImageGlass.frmMain.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3132.0 built by: NET472REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 5.5.7.26
    Win32 Version: 5.5.7.26
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3151.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 5.5.6778.38272
    Win32 Version: 5.5.6778.38272
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 5.5.6778.38271
    Win32 Version: 5.5.6778.38271
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.Library
    Assembly Version: 5.5.6778.38271
    Win32 Version: 5.5.6778.38271
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FileWatcherEx
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/FileWatcherEx.DLL
----------------------------------------
ImageGlass.Theme
    Assembly Version: 5.5.6778.38272
    Win32 Version: 5.5.6778.38272
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 5.5.0.0
    Win32 Version: 5.5.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.4
    Win32 Version: 11.0.0.4
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.5.0.0
    Win32 Version: 7.5.0.1
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3160.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

### To Reproduce
1. Re-install the program
2. Delete the program settings from registry `HKEY_CURRENT_USER\Software\PhapSoftware\ImageGlass`
3. Restart Windows

**Comment by fire-eggs** [comment]
Confirmed on Windows 10; doesn't happen on Windows 7 !?

**Comment by motaz-alnuweiri** [comment]
I tested `ImageGlass Moon v5.5.9.5` on `Windows 7` and `Windows 10` and the bug is fixed no more error messages, Thank you 😄
