### ISSUE TITLE
Improve error message when opening invalid image data from clipboard

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#865]
### System information:
 - Windows OS version: Win7
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Copy some text into the clipboard [see additional context below].
2. Run imageglass
3. Open an image from the clipboard.

### Actual behavior:
ImageGlass crashes.

Unhandled exception error details:
```
System.Exception: Base-64 file content is invalid.
   at ImageGlass.Heart.Photo.ConvertBase64ToBytes(String content)
   at ImageGlass.Heart.Photo.ConvertBase64ToBitmap(String content)
   at ImageGlass.frmMain.mnuMainOpenImageData_Click(Object sender, EventArgs e)
```

### Expected behavior:
ImageGlass produces an error message to the effect of "clipboard does not contain image data".

### Additional context:

The text I happened to have in the clipboard at the time was:
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ImageGlass.frmMain.<mnuMainSaveAs_Click>d__133.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by d2phap** [comment]
Done in the latest build of IG Moon https://imageglass.org/moon
