### ISSUE TITLE
Crashed in Settings if using custom ThumbnailDimension

### ISSUE THREAD

**Issue by PowershellScripter** [d2phap/ImageGlass#967]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.0.12.8

Installing v8.0.12.8, consistent issues with the admin config file.
First was users not being able to open imageglass with admin config file in place, which I was only able to resolve by modifying the registry to run the program as admin. 

This issue has been reported and still not responded to.
[AdminConfigIssue](https://github.com/d2phap/ImageGlass/issues/943)

Second issue is unhandled exception after adding admin config:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageGlass.frmSetting.ApplySettings()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 8.0.12.8
    Win32 Version: 8.0.12.8
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 8.0.7645.27245
    Win32 Version: 8.0.7645.27245
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
ImageGlass.Base
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Base.DLL
----------------------------------------
ImageGlass.Settings
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Settings.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Library
    Assembly Version: 8.0.7645.27244
    Win32 Version: 8.0.7645.27244
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.UI
    Assembly Version: 8.0.7645.27245
    Win32 Version: 8.0.7645.27245
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.UI.DLL
----------------------------------------
ImageGlass.Heart
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Heart.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Magick.NET-Q16-OpenMP-x64
    Assembly Version: 7.22.2.0
    Win32 Version: 7.22.2.2
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-OpenMP-x64.DLL
----------------------------------------
Magick.NET.Core
    Assembly Version: 5.2.2.0
    Win32 Version: 5.2.2.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET.Core.DLL
----------------------------------------
Magick.NET.SystemDrawing
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET.SystemDrawing.DLL
----------------------------------------
FileWatcherEx
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/FileWatcherEx.DLL
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 8.0.7645.27244
    Win32 Version: 8.0.7645.27244
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.7
    Win32 Version: 11.0.0.7
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by d2phap** [comment]
Hi @NinjaRMMTheming

About
> This issue has been reported and still not responded to. #943 

No worry for your issues created here, I do read them all.
I only reply if I need more information or to inform the issue is fixed.

Thanks!

**Comment by PowershellScripter** [comment]
My Apologies

&

Thank You!






________________________________

**Comment by d2phap** [comment]
Hi @NinjaRMMTheming 

I have tried adding `igconfig.admin.xml` as steps you described, IG works well.
- What is the installed folder of IG?
- Can you send me your admin config?


![image](https://user-images.githubusercontent.com/3154213/106275093-48130f80-6270-11eb-9de8-147ac71f09fa.png)

**Comment by PowershellScripter** [comment]
@d2phap 

Default installed Folder: 'C:\Program Files\ImageGlass'

Admin Config:


```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="IsSlideshow" value="False" />
      <Item key="IsShowSlideshowCountdown" value="True" />
      <Item key="IsRandomSlideshowInterval" value="False" />
      <Item key="IsFullScreen" value="False" />
      <Item key="IsShowThumbnail" value="True" />
      <Item key="IsCenterImage" value="True" />
      <Item key="IsColorPickerRGBA" value="True" />
      <Item key="IsColorPickerHEXA" value="True" />
      <Item key="IsColorPickerHSLA" value="True" />
      <Item key="IsColorPickerHSVA" value="True" />
      <Item key="IsShowWelcome" value="True" />
      <Item key="IsShowToolBar" value="True" />
      <Item key="IsShowThumbnailScrollbar" value="False" />
      <Item key="IsLoopBackSlideshow" value="True" />
      <Item key="IsLoopBackViewer" value="True" />
      <Item key="IsPressESCToQuit" value="True" />
      <Item key="IsShowCheckerBoard" value="False" />
      <Item key="IsAllowMultiInstances" value="True" />
      <Item key="IsWindowAlwaysOnTop" value="False" />
      <Item key="IsWindowFrameless" value="False" />
      <Item key="IsThumbnailHorizontal" value="False" />
      <Item key="IsConfirmationDelete" value="False" />
      <Item key="IsScrollbarsVisible" value="False" />
      <Item key="IsSaveAfterRotating" value="False" />
      <Item key="IsPreserveModifiedDate" value="True" />
      <Item key="IsNewVersionAvailable" value="False" />
      <Item key="IsDisplayBasenameOfImage" value="False" />
      <Item key="IsCenterToolbar" value="True" />
      <Item key="IsOpenLastSeenImage" value="False" />
      <Item key="IsApplyColorProfileForAll" value="False" />
      <Item key="IsShowNavigationButtons" value="False" />
      <Item key="IsShowCheckerboardOnlyImageRegion" value="False" />
      <Item key="IsRecursiveLoading" value="False" />
      <Item key="IsUseFileExplorerSortOrder" value="True" />
      <Item key="IsGroupImagesByDirectory" value="False" />
      <Item key="IsShowingHiddenImages" value="False" />
      <Item key="IsShowColorPickerOnStartup" value="False" />
      <Item key="IsShowPageNavOnStartup" value="False" />
      <Item key="IsShowPageNavAuto" value="False" />
      <Item key="IsWindowFit" value="True" />
      <Item key="IsCenterWindowFit" value="True" />
      <Item key="IsShowToast" value="True" />
      <Item key="IsUseTouchGesture" value="True" />
      <Item key="IsHideTooltips" value="False" />
      <Item key="IsExifToolAlwaysOnTop" value="True" />
      <Item key="IsUseEmptyTitleBar" value="False" />
      <Item key="FirstLaunchVersion" value="5" />
      <Item key="SlideShowInterval" value="5" />
      <Item key="SlideShowIntervalTo" value="5" />
      <Item key="ThumbnailDimension" value="100" />
      <Item key="ThumbnailBarWidth" value="148" />
      <Item key="ImageBoosterCachedCount" value="1" />
      <Item key="ZoomLockValue" value="100" />
      <Item key="ToolbarIconHeight" value="22" />
      <Item key="ImageEditQuality" value="100" />
      <Item key="FrmMainWindowState" value="Normal" />
      <Item key="FrmSettingsWindowState" value="Normal" />
      <Item key="FrmExifToolWindowState" value="Normal" />
      <Item key="ImageLoadingOrder" value="Name" />
      <Item key="ImageLoadingOrderType" value="Asc" />
      <Item key="MouseWheelAction" value="Zoom" />
      <Item key="MouseWheelCtrlAction" value="ScrollVertically" />
      <Item key="MouseWheelShiftAction" value="ScrollHorizontally" />
      <Item key="MouseWheelAltAction" value="BrowseImages" />
      <Item key="ZoomMode" value="AutoZoom" />
      <Item key="ZoomOptimizationMethod" value="Auto" />
      <Item key="ToolbarPosition" value="Top" />
      <Item key="AfterEditingAction" value="Nothing" />
      <Item key="ColorProfile" value="sRGB" />
      <Item key="ToolbarButtons" value="btnPrint;btnOpen;btnConvert;btnRefresh;btnZoomIn;btnZoomOut;btnActualSize;btnRotateLeft;btnRotateRight;btnFlipHorz;btnFlipVert;btnDelete;" />
      <Item key="AutoUpdate" value="0" />
      <Item key="LastSeenImagePath" value="C:\Program Files\ImageGlass\default.png" />
      <Item key="ExifToolExePath" value="" />
      <Item key="ZoomLevels" value="5;10;15;20;30;40;50;60;70;80;90;100;125;150;175;200;250;300;350;400;500;600;700;800;1000;1200;1500;1800;2100;2500;3000;3500" />
      <Item key="EditApps" value="[.avif|||][.b64|||][.bmp|||][.cur|||][.cut|||][.dds|||][.dib|||][.emf|||][.exif|||][.gif|||][.heic|||][.heif|||][.ico|||][.jfif|||][.jp2|||][.jpe|||][.jpeg|||][.jpg|||][.pbm|||][.pcx|||][.pgm|||][.png|||][.ppm|||][.psb|||][.svg|||][.tif|||][.tiff|||][.webp|||][.wmf|||][.wpg|||][.xbm|||][.xpm|||][.exr|||][.hdr|||][.psd|||][.tga|||][.3fr|||][.ari|||][.arw|||][.bay|||][.crw|||][.cr2|||][.cr3|||][.cap|||][.dcs|||][.dcr|||][.dng|||][.drf|||][.eip|||][.erf|||][.fff|||][.gpr|||][.iiq|||][.k25|||][.kdc|||][.mdc|||][.mef|||][.mos|||][.mrw|||][.nef|||][.nrw|||][.obm|||][.orf|||][.pef|||][.ptx|||][.pxn|||][.r3d|||][.raf|||][.raw|||][.rwl|||][.rw2|||][.rwz|||][.sr2|||][.srf|||][.srw|||][.x3f|||]" />
      <Item key="AllFormats" value="*.avif;*.b64;*.bmp;*.cur;*.cut;*.dds;*.dib;*.emf;*.exif;*.gif;*.heic;*.heif;*.ico;*.jfif;*.jp2;*.jpe;*.jpeg;*.jpg;*.pbm;*.pcx;*.pgm;*.png;*.ppm;*.psb;*.svg;*.tif;*.tiff;*.webp;*.wmf;*.wpg;*.xbm;*.xpm;*.exr;*.hdr;*.psd;*.tga;*.3fr;*.ari;*.arw;*.bay;*.crw;*.cr2;*.cr3;*.cap;*.dcs;*.dcr;*.dng;*.drf;*.eip;*.erf;*.fff;*.gpr;*.iiq;*.k25;*.kdc;*.mdc;*.mef;*.mos;*.mrw;*.nef;*.nrw;*.obm;*.orf;*.pef;*.ptx;*.pxn;*.r3d;*.raf;*.raw;*.rwl;*.rw2;*.rwz;*.sr2;*.srf;*.srw;*.x3f;" />
      <Item key="KeyComboActions" value="LeftRight:PrevNextImage;PageUpDown:PrevNextImage;SpaceBack:PauseSlideshow;UpDown:PauseSlideshow;" />
      <Item key="BackgroundColor" value="#171717" />
      <Item key="FrmSettingsWindowBound" value="-1241;-191;1050;750" />
      <Item key="Language" value="English" />
      <Item key="Theme" value="Material_Fun_Dark" />
      <Item key="FrmMainWindowBound" value="199;38;2084;1363" />
      <Item key="FrmExifToolWindowBound" value="280;125;800;600" />
    </Content>
  </Configuration>
</ImageGlass>
```

**Comment by d2phap** [comment]
The problem is you used a custom value for `ThumbnailDimension`, and this is not relevant to `igconfig.admin.xml` file.

```xml
<Item key="ThumbnailDimension" value="100" />
```

![image](https://user-images.githubusercontent.com/3154213/106343867-7fba9f80-62e2-11eb-8cf8-c8fb61f79b82.png)

### Steps to reproduce:
- Open `igconfig.xml` file (or `igconfig.admin.xml`),
- Change `ThumbnailDimension` to `100`
- Save change
- Run ImageGlass, go to Settings
- Click OK or Apply button
- See error

You should have mentioned the steps clearly so that it's easier to find the bug.
Anyway, thanks for the report.

**Comment by PowershellScripter** [comment]
There was no way for me to mention the steps clearly as anything I did in imageglass was resulting in that error from the admin config, so I could not determine what specifically was causing the error.

And the Thumbnail deminsion attribute is not one I have ever changed, it came with the config file. Anyways, I appreciate the fix. No more exception error. Thanks.
